'use server';

import { auth, currentUser } from '@clerk/nextjs/server';
import { revalidatePath } from 'next/cache';
import { supabaseAdmin } from '@/lib/supabaseAdmin';
import { generateDisplayName, isGeneratedName } from '@/lib/displayNames';
import type { Gender } from '@/lib/types';

async function nameTaken(name: string) {
  const { data } = await supabaseAdmin().from('users').select('id').eq('display_name', name).maybeSingle();
  return !!data;
}

export async function rerollDisplayName() {
  if (!auth().userId) throw new Error('Unauthorised');
  for (let i = 0; i < 5; i++) {
    const n = generateDisplayName();
    if (!(await nameTaken(n))) return n;
  }
  return generateDisplayName();
}

export async function completeOnboarding(input: { gender: Gender; displayName: string }) {
  const { userId } = auth();
  if (!userId) return { error: 'Sign in first' };
  if (!['male', 'female', 'other'].includes(input.gender)) return { error: 'Pick a gender' };
  if (!isGeneratedName(input.displayName)) return { error: 'That name was not generated by us — reroll one.' };
  if (await nameTaken(input.displayName)) return { error: 'Someone just took that name. Reroll!' };

  const user = await currentUser();
  const realName = [user?.firstName, user?.lastName].filter(Boolean).join(' ') || user?.username || '';
  const email = user?.primaryEmailAddress?.emailAddress ?? user?.emailAddresses[0]?.emailAddress ?? '';

  const { error } = await supabaseAdmin().from('users').upsert(
    {
      clerk_id: userId,
      display_name: input.displayName,
      gender: input.gender,
      real_name: realName,
      email,
      is_online: true,
      last_seen: new Date().toISOString(),
    },
    { onConflict: 'clerk_id' },
  );
  if (error) return { error: 'Could not save your profile. Try again.' };

  revalidatePath('/dashboard');
  return { ok: true };
}
